language: node_js

node_js:
  - "7"

cache:
  yarn: true

before_script:
  - node_modules/.bin/flow-typed install
  - node_modules/.bin/flow check

script:
  - npm run lint
  - npm test

after_success:
  - npm run coverage
