language: node_js

node_js:
  - "7"

sudo: required

# cache:
#   yarn: true

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

before_script:
  - node node_modules/chromedriver/install.js
  - node node_modules/phantomjs-prebuilt/install.js

script:
  # - sleep 10
  - npm run lint
  - npm test

after_success:
  - npm install coveralls && cat test/unit/coverage/lcov.info | coveralls
